### ISSUE TITLE
3.1.6 and multiple monitors

### ISSUE THREAD

**Issue by netsonicyxf** [samsonwang/LaunchyQt#111] opened 2023-07-18 04:20 UTC
OS: Win 10 x64

Issue:
1. I have 3 monitors, but 3.1.6 only detect 2 of them.
![image](https://github.com/samsonwang/LaunchyQt/assets/43513391/eaf8017f-dcc6-4f20-8704-0ccc35c1cf62)
![image](https://github.com/samsonwang/LaunchyQt/assets/43513391/2043f0b7-02bc-4e1b-bc7c-d8e4259c1021)

2. When I run Launch, it always show window on monitor 3. 
After I drag it to monitor **2**, it still show window on monitor 3 in the next time

**Comment by teknowledgist** [comment] 2023-08-02 19:09
I have two monitors, and LaunchyQT (v3.1.6) will only recognize one of them in the menu.  Further, the menu shows `Screen 1`, but the LaunchyQT window will only appear on screen 2.  I can drag it over to screen 1, but it opens the next time on Screen 2.  
![image](https://github.com/samsonwang/LaunchyQt/assets/3977744/9307364d-54da-4509-8b4e-a1052da41112)

The problem is Screen 2 is dedicated to VMs, some of which also run LaunchyQT, so it gets a bit confusing.

**Comment by samsonwang** [comment] 2023-12-11 14:09
fixed in v3.1.7

**Closed by samsonwang** 2023-12-11 14:09 UTC
